version: "3.9"

services:
  kysely_codegen_adminer:
    container_name: kysely_codegen_adminer
    image: adminer
    ports:
      - 8081:8080
    restart: always
  kysely_codegen_libsql:
    container_name: kysely_codegen_libsql
    image: ghcr.io/libsql/sqld:latest
    ports:
      - 8080:8080
    restart: always
  kysely_codegen_mysql:
    container_name: kysely_codegen_mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
  kysely_codegen_postgres:
    container_name: kysely_codegen_postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    image: postgres:latest
    ports:
      - 5433:5432
    restart: always
  kysely_codegen_clickhouse:
    container_name: kysely_codegen_clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    image: clickhouse/clickhouse-server:latest
    ports:
      - 8123:8123
      - 9000:9000
    restart: always
